
name: Deploy to Databricks
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: 'Select the Environment'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: notify the username to channel
        run: |
        curl -X POST -H 'Content-Type: application/json' --data '{"text": "${{ github.actor }} is running the pipeline"}' ${{ secrets.TEAMS_WEBHOOK }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.11.5' # Change to your Python version if needed

      - name: Install Databricks CLI
        run: pip install databricks-cli

      - name: Deploy to Databricks
        run: |
          echo ${{ vars.DATABRICKS_HOST }}
          touch tfile
          echo ${{ secrets.DATABRICKS_TOKEN }} > tfile
          databricks configure --host='${{ vars.DATABRICKS_HOST }}' --token-file tfile

          NOTEBOOK_PATH=notebooks/
          REMOTE_PATH=/hemant/notebooks/

          # Create or update the notebook
          databricks workspace import_dir -o "$NOTEBOOK_PATH" "$REMOTE_PATH"

          rm -rf tfile