name: Deploy to multi env Databricks
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
    DEV_deployment:
        name: Deploy on DEV
        if: contains(github.event.head_commit.message, '#DeployOnDev')
        uses: devops-hemant/centralized/.github/workflows/dev.yml@main
        with:
            environment: dev
        secrets: inherit

    STG_deployment:
        name: Deploy on STG
        if: contains(github.event.head_commit.message, '#DeployOnStg')
        uses: devops-hemant/centralized/.github/workflows/stg.yml@main

    PROD_deployment:
        name: Deploy on PROD
        if: contains(github.event.head_commit.message, '#DeployOnProd')
        uses: devops-hemant/centralized/.github/workflows/prod.yml@main


