name: Deploy to multi env Databricks
on:
  push:
  workflow_dispatch:
  issue_comment:
    types: [created, edited, deleted]

jobs:
    DEV_check:
      name: check if dev deployment is there.
      runs-on: ubuntu-latest
      steps:
       - name: check the commit text
         run: |
            echo ${{github.event.comment.body}}

    # DEV_deploy:
    #     name: run DEV action
    #     needs: DEV_check
    #     uses: devops-hemant/centralized/.github/workflows/dev.yml@main"

    STG_check:
        name: check if dev deployment is there.
        runs-on: ubuntu-latest
        steps:
         - name: check the commit text
           run: |
              echo ${{github.event.comment.body}}

    # STG:
    #     name: run STG action
    #     needs: STG_check
    #     uses: devops-hemant/centralized/.github/workflows/stg.yml@main

    PROD_check:
      name: check if dev deployment is there.
      runs-on: ubuntu-latest
      steps:
       - name: check the commit text
         run: |
            echo ${{github.event.comment.body}}

    # PROD:
    #     name: run PROD action
    #     needs: PROD_check
    #     uses: devops-hemant/centralized/.github/workflows/prod.yml@main


