name: Deploy to multi env Databricks
on:
  push:
  workflow_dispatch:
  issue_comment:
    types: [created, edited, deleted]

jobs:
    DEV:
        if: contains(github.event.comment.body, 'dev')
        uses: devops-hemant/centralized/.github/workflows/dev.yml@main

    STG1:
        if: contains(github.event.comment.body, 'stg')
        uses: devops-hemant/centralized/.github/workflows/stg.yml@main

    PROD:
        if: contains(github.event.comment.body, 'prod')
        uses: devops-hemant/centralized/.github/workflows/prod.yml@main


