name: Deploy to multi env Databricks
on:
  push:
  workflow_dispatch:
  issue_comment:
    types: [created, edited, deleted]

jobs:
    # DEV_check:
    #   name: check if dev deployment is there.
    #   runs-on: ubuntu-latest
    #   continue-on-error: true
    #   steps:
    #    - name: check the commit text
    #      run: |
    #         echo ${{ github.event.head_commit.message }} | grep -o "deploy on dev"


    DEV_deploy:
        name: run DEV action
        # needs: DEV_check
        if: contains(github.event.head_commit.message, 'deploy on dev')
        uses: devops-hemant/centralized/.github/workflows/dev.yml@main

    # STG_check:
    #     name: check if dev deployment is there.
    #     runs-on: ubuntu-latest
    #     continue-on-error: true
    #     steps:
    #      - name: check the commit text
    #        run: |
    #           echo ${{ github.event.head_commit.message }} | grep -o "deploy on stg"

    # STG_deploy:
    #     name: run STG action
    #     needs: STG_check
    #     uses: devops-hemant/centralized/.github/workflows/stg.yml@main

    # PROD_check:
    #   name: check if dev deployment is there.
    #   runs-on: ubuntu-latest
    #   continue-on-error: true
    #   steps:
    #    - name: check the commit text
    #      run: |
    #         echo ${{ github.event.head_commit.message }} | grep -o "deploy on prod"

    # PROD_deploy:
    #     name: run PROD action
    #     needs: PROD_check
    #     uses: devops-hemant/centralized/.github/workflows/prod.yml@main


