name: Deploy to multi env Databricks
on:
  push:
  workflow_dispatch:
  issue_comment:
    types: [created, edited, deleted]

jobs:
    DEV_check:
      name: check if dev deployment is there.
      runs-on: ubuntu-latest
      steps:
       - name: check the commit text
         run: |
            echo ${{github.event.comment.body}}

       - name: run action
         uses: devops-hemant/centralized/.github/workflows/dev.yml@main"


    STG:
        if: contains(github.event.comment.body, 'stg')
        uses: devops-hemant/centralized/.github/workflows/stg.yml@main

    PROD:
        if: contains(github.event.comment.body, 'prod')
        uses: devops-hemant/centralized/.github/workflows/prod.yml@main


