name: branches merge

on: 
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: 'Select the Environment'
        required: true
      

jobs:
  merging:
    runs-on: ubuntu-latest
    outputs:
      current_branch: ${{ steps.extract_branch.outputs.branch }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.environment }}

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Git push
        #if: github.event_name != 'pull_request'
        run: |
          set -x
          git branch
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch
          git pull
          git checkout ${{ steps.extract_branch.outputs.branch }}
          git checkout ${{ inputs.environment }}
          git merge ${{ steps.extract_branch.outputs.branch }}
          git push
