name: Deploy with State Tracking

on:
  workflow_dispatch:
  push:
    branches:
      - dev

env:
  FEATURE_NUMBER: "FEAT-${{ github.run_number }}"
  RUN_NUMBER: ${{ github.run_number }}
  TEAM: "teamHS"
  RELEASE_NUMBER: "CHG123456"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          ref: ${{ github.ref}}

      # 🚀 Step 2 — Deploy website
      - name: Upload website
        run: |
          az storage blob upload-batch \
            --account-name ${{ vars.AZURE_STORAGE_ACCOUNT }} \
            --destination '$web' \
            --source ./report \
            --sas-token "${{ secrets.AZSAS }}" \
            --overwrite

      - name: Update Releases
        run: |

            # ===== CONFIG =====
            ACCOUNT="${{ vars.AZURE_STORAGE_ACCOUNT }}"
            CONTAINER="\$web"   # or your container
            SAS_TOKEN="${{ secrets.AZSAS }}"   # ?sv=... (keep the ?)
            RELEASE="Release-CHG001"
            OUTPUT="output.csv"

            if [ -z "$RELEASE" ]; then
              echo "Usage: ./generate_csv.sh Release-CHG001"
              exit 1
            fi

            echo "Downloading $RELEASE ..."

            # Download release folder using SAS
            set -x
            az storage blob download-batch \
              --account-name "$ACCOUNT" \
              --source "$CONTAINER" \
              --destination "./tmp" \
              --pattern "$RELEASE/*" \
              --sas-token "$SAS_TOKEN"
            set +x

            # Create CSV header
            echo "Release,Repo,ID,Filename,Status" > "$OUTPUT"

            echo "Processing files..."

            # Traverse files
            find "./tmp/$RELEASE" -type f | while read file; do
              # Remove prefix
              path=${file#./tmp/}

              # Split path
              IFS='/' read -r rel repo id status filename <<< "$path"

              # Skip if structure not matching
              if [ -z "$filename" ]; then
                continue
              fi

              echo "$rel,$repo,$id,$filename,$status" >> "$OUTPUT"
            done

            echo "CSV generated: $OUTPUT"

            # Cleanup
            rm -rf ./tmp

            az storage blob upload \
              --account-name "$ACCOUNT" \
              --container-name '$web' \
              --name "$RELEASE/data.csv" \
              --file "$OUTPUT" \
              --sas-token "$SAS_TOKEN" \
              --overwrite
      