name: Deploy with State Tracking

on:
  workflow_dispatch:
  push:
    branches:
      - dev

env:
  FEATURE_NUMBER: "FEAT-${{ github.run_number }}"
  RUN_NUMBER: ${{ github.run_number }}
  TEAM: "teamHS"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      # 🚀 Step 2 — Deploy website
      - name: Upload website
        run: |
          az storage blob upload-batch \
            --account-name ${{ vars.AZURE_STORAGE_ACCOUNT }} \
            --destination '$web' \
            --source ./report \
            --sas-token "${{ secrets.AZSAS }}" \
            --overwrite

      # ✅ Step 3 — Mark SUCCESS
      - name: Set state = success
        run: |
          echo "${{ github.repository }} ${{ env.FEATURE_NUMBER }} ${{ env.TEAM }} file1 SUCCESS" >> $RUN_NUMBER.txt
          echo "${{ github.repository }} ${{ env.FEATURE_NUMBER }} ${{ env.TEAM }} file2 FAILED" >> $RUN_NUMBER.txt
          echo "${{ github.repository }} ${{ env.FEATURE_NUMBER }} ${{ env.TEAM }} file3 SUCCESS" >> $RUN_NUMBER.txt

          az storage blob upload \
            --account-name ${{ vars.AZURE_STORAGE_ACCOUNT }} \
            --container-name '$web' \
            --name state/$RUN_NUMBER.txt \
            --file $RUN_NUMBER.txt \
            --sas-token "${{ secrets.AZSAS }}" \
            --overwrite
